### PR TITLE
New trigger configuration parameter raw_output & Russian translation improved

### PR DESCRIPTION
**Pull request by AleksandrSokolov**
1. New trigger configuration parameter raw_output. This makes more control on API Call.
2. Russian translation improved

### CODE REVIEW

**Comment by AleksandrSokolov** [comment]
@glutamate please review

**Comment by glutamate** [comment]
@AleksandrSokolov thank you for the work on translation, this is a great effort.

With respect to the raw output. I recognise that there is a problem here because sometimes you should be able to set the output. I don't think the place where you put the configuration option is the best location (for instance it only affects one action( but I'm also not sure where to put it instead. Ideally this would be a property of all api actions. Let me just see if this is possible.

**Comment by glutamate** [comment]
moved to #2450

**Comment by glutamate** [comment]
@AleksandrSokolov currently the "raw output" is less raw than expected - if i `return {x:1}` the api response is `{resp: {x:1}}`

I am probably changing this so it is not wrapped in `resp`, is this ok with you

**Comment by glutamate** [comment]
Implmented in #2612

**Pull request closed without merging**
