### PR TITLE
Fix unique view name check for create and edit of view. Simplify urls for actions.js router to be more simular to viewedit.js.

### PR DESCRIPTION
**Pull request by AleksandrSokolov**
[+]Fix unique view name check for create and edit of view (viewedit.js).
[+]Simplify urls for actions.js router to be more simular to viewedit.js. (replace /actions/trigger/new with /actions/new, etc)

### CODE REVIEW

**Comment by AleksandrSokolov** [comment]
@glutamate there are still many problems with form for create user / update user:
* email can be empty
* validators are not defined
* promts for fields are not defined
* required and is_unique doens work 

Please help with this

  Field {
    label: 'Email',
    name: 'email',
    fieldview: undefined,
    validator: [Function (anonymous)],
    showIf: undefined,
    parent_field: undefined,
    postText: undefined,
    class: '',
    id: 1,
    default: undefined,
    sublabel: undefined,
    description: '',
    type: {
      name: 'String',
      sql_name: 'text',
      attributes: [Array],
      contract: [Function: contract],
      fieldviews: [Object],
      read: [Function: read],
      presets: [Object],
      validate: [Function: validate],
      validate_attributes: [Function: validate_attributes]
    },
    options: undefined,
    required: true,
    is_unique: true,
    hidden: false,
    disabled: false,
    calculated: false,
    primary_key: false,
    stored: false,
    expression: null,
    sourceURL: undefined,
    is_fkey: false,
    input_type: 'fromtype',
    attributes: {},
    table_id: 1
  }
]

**Comment by glutamate** [comment]
ok, I'll take a look at this today.

**Comment by glutamate** [comment]
I'm seeing some bugs in the user table code, fixing now

**Comment by glutamate** [comment]
Thanks, merged - working on user form on #793

**Comment by AleksandrSokolov** [comment]
@glutamate Thank you!!!

**Pull request merged**
