### PR TITLE
New config var "backup_file_prefix" and more internationalization

### PR DESCRIPTION
**Pull request by AleksandrSokolov**
1) New config var "backup_file_prefix"
2) More internationalization
3) Update Russian translation
4) Fix https://github.com/saltcorn/saltcorn/issues/1768
5) Add verbose flag and more clear cli args description for backup cli command.
6) Add message that Database Backup using pg_dump is supported only for PostgreSQL.
7) Add Admin UI for backup file prefix.
8) Add support of backup folders for destination "Saltcorn files". Now you can choose folder inside Saltcorn file storage to backup files. 
9) Fix some minor issues in Admin backup UI.

### CODE REVIEW

**Comment by AleksandrSokolov** [comment]
@glutamate Please review.

**Comment by glutamate** [comment]
thank you @AleksandrSokolov, this looks great, but how does the user set the backup file prefix? If you're not sure how to do this then I can add it?

**Comment by AleksandrSokolov** [comment]
@glutamate It seems to me that it would be more convenient to make 2 levels of tabs.
If you show me an example of how to do this, I would gradually redo the entire administrative part - we have a lot of screens, where there are a lot of parameters and the screens are too long.
image

**Comment by AleksandrSokolov** [comment]
@glutamate I added UI for backup_file_prefix.

**Comment by glutamate** [comment]
@AleksandrSokolov thank you so much. I am away today but will have a look later

**Comment by glutamate** [comment]
I will merge this and then make some minor adjustments (order, headers) in my next PR.

**Pull request merged**
