### PR TITLE
Discovery tables improvement. Russian localization. Some documentation.

### PR DESCRIPTION
**Pull request by AleksandrSokolov**
Improve table discovery: Add mapping for smallint, bigint, numeric, char,varchar, date. 
Fix the problem "Table not found" for discovered tables. 
Improve localization for discovery, tenants. 
Improve russian translation. 
Fix problem with ar.json translation (add comma). 
Add some documenation comments to other modules.

### CODE REVIEW

**Comment by glutamate** [comment]
I'm trying to figure out the CI test failure

**Comment by AleksandrSokolov** [comment]
> I'm trying to figure out the CI test failure
@glutamate 

May be problem with packages/server/package-lock.json.

Perhaps I shouldn't have added it to the commit.

**Comment by AleksandrSokolov** [comment]
@glutamate May be i need to recreate pull request without packages/server/package-lock.json. Let me know.

**Comment by glutamate** [comment]
no i figured it out @AleksandrSokolov . please merge master or cherry pick https://github.com/saltcorn/saltcorn/commit/39ebf37bd5e2083d7bee730e4a33ca774d1dd821 into this PR

**Comment by glutamate** [comment]
if there are conflicts, just merge my changes to package.json and rerun `lerna bootstrap` to regenerate the lock file.

**Comment by AleksandrSokolov** [comment]
> if there are conflicts, just merge my changes to package.json and rerun `lerna bootstrap` to regenerate the lock file.

ok, I'll do this today later.

**Pull request closed without merging**
